config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :todos
  resources :contact
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
    @todos = Todo.order(:updated_at).page params[:page]
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(todos_params)

    if @todo.save
      flash[:notice] = 'Todo added successfully!'
      redirect_to todos_path
    else
      flash[:notice] = 'Todo NOT created!'
      render 'new'
    end
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todos_params)
      flash[:notice] = 'Todo successfully updated!'
      redirect_to todos_path
    else
      flash[:notice] = 'Todo NOT updated!'
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    if @todo.destroy
      flash[:notice] = 'Todo successfully deleted!'
      redirect_to todos_path
    else
      flash[:notice] = 'Todo not deleted. Try again.'
    end
  end

  private
  def todos_params
    params.require(:todo).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Helper for formatting the last modified field
  def pretty_date(d)
    d.strftime('%B %e, %Y %H:%M')
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/contact/index.html.erb
<%= provide(:title, 'Contact') %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
  <div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'Todo Rails', root_path, class: 'navbar-brand' %>

  </div>
  <div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Todos', todos_path %></li>
      <li class="active"><a href="">Contact</a></li>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</nav>

<div class="container">

<div class="starter-template">
  <h1>Contact</h1>
  <p class="lead">Like this app, contact me below to discuss, hire or collaborate.</p>
  <%= link_to "Twitter", "https://twitter.com/Macabhaird" %> |
  <%= link_to "Github", "https://github.com/rosswd" %> |
  <%= mail_to "rw@kraton.33mail.com", "Email" %>
</div>

</div><!-- /.container -->

app/views/home/index.html.erb
<%= provide(:title, 'Home') %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
  <div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'Todo Rails', root_path, class: 'navbar-brand' %>

  </div>
  <div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Todos', todos_path %></li>
      <li><%= link_to 'Contact', contact_index_path %></li>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</nav>

<div class="container">

<div class="starter-template">
  <h1>Todo Rails</h1>
  <p class="lead">A simple todo list application written in Ruby on Rails by Ross Ward.</p>
</div>

</div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | TodoRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo, html: {class: 'form-horizontal'}) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todo.errors.count, 'error') %>
            prevented this task from being saved:
      </h2>
      <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Enter a task' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control',
            placeholder: 'Optionally, enter a description' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
      <%= link_to "Cancel", todos_path %>
    </div>
  </div>

<% end %>

app/views/todos/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Todo Rails', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

app/views/todos/edit.html.erb
<% provide(:title, 'Edit Task') %>

<%= render 'nav' %>
        <li><%= link_to 'Todos', todos_path %></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
<h1>Edit Task</h1>

<%= render 'form' %>
</div>

app/views/todos/index.html.erb
<% provide(:title, 'All Tasks') %>

<%= render 'nav' %>
      <li class="active"><a href="#">Todos</a></li>
      <li><%= link_to "Contact", contact_index_path %></li>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</nav>

<div class="container">
  <% if flash[:notice] %>
    <div class="notice alert alert-success"><%= flash[:notice] %></div>
  <% end %>

<h1>All Tasks</h1>

<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Last Modified</th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
    <tr>
      <td><%= link_to todo.title, todo_path(todo) %></td>
      <td><%= todo.description %></td>
      <td><%= pretty_date(todo.updated_at) %></td>
      <td>
        <%= link_to edit_todo_path(todo), class: 'btn btn-default btn-sm' do %>
        Edit
        <%= content_tag(:span, "", class: 'glyphicon glyphicon-pencil') %>
        <% end %>
      </td>
      <td><%= link_to todo,
        method: :delete,
        data: { confirm: 'Are you sure?' },
        class: 'btn btn-success btn-sm' do %> Done
        <%= content_tag(:span, "", class: 'glyphicon glyphicon-ok') %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Add Task', new_todo_path, class: 'btn btn-primary btn-default' %>

<%= paginate @todos %> <br>
<%= page_entries_info @todos %>
</div>

app/views/todos/new.html.erb
<% provide(:title, 'Add Task') %>

<%= render 'nav' %>
        <li><%= link_to 'Todos', todos_path %></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
<h1>Add New Task</h1>
<% if flash[:notice] %>
    <div class="notice alert alert-danger"><%= flash[:notice] %></div>
  <% end %>

<%= render 'form' %>

app/views/todos/show.html.erb
<% provide(:title, 'Task Detail') %>
<%= render 'nav' %>
        <li><%= link_to 'Todos', todos_path %></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
<h1>Title: <%= @todo.title %></h1>

<h2>Description:</h2>
<p><%= @todo.description %></p>

<p>
  Last Modified: <%= pretty_date(@todo.updated_at) %>
</p>

<%= link_to 'Back', todos_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_todo_path, class: 'btn btn-warning' %>